# GitHub Copilot Advanced Configuration

# Code suggestion behavior
suggestions:
  autoThreshold: medium  # Confidence threshold for inline suggestions
  contextLines: 100      # Number of surrounding lines to consider for context
  
# Reference documentation
references:
  includeDocumentation: true
  maxReferences: 10
  prioritizeSameDomain: true
  
# Security settings
security:
  blockUnsafeCode: true
  sensitiveDataDetection: true
  
# Performance settings
performance:
  caching: true
  prefetching: true
  
# Workspace behavior
workspace:
  filesLimit: 200
  syncInterval: 30
  ignorePatterns:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "**/*.min.js"
    - "**/*.min.css"

# Learning from repository
learning:
  enabled: true
  adaptToRepositoryStyle: true
  rememberUserPreferences: true

# Extension behavior
extensions:
  vscode:
    inlineSuggestions: true
    ghostText: true
  visualStudio:
    inlineSuggestions: true
  jetbrains:
    inlineSuggestions: true