# GitHub Copilot main configuration file
# Documentation: https://docs.github.com/en/copilot/overview-of-github-copilot

version: 1

features:
  # GitHub Copilot Chat: https://docs.github.com/en/copilot/github-copilot-chat/about-github-copilot-chat
  chat: true
  # GitHub Copilot CLI: https://docs.github.com/en/copilot/github-copilot-in-the-cli/about-github-copilot-in-the-cli
  cli: true
  # GitHub Copilot for Pull Requests: https://docs.github.com/en/copilot/github-copilot-for-pull-requests/about-github-copilot-for-pull-requests
  pullRequests: true
  # GitHub Copilot for Issues: https://docs.github.com/en/copilot/github-copilot-for-issues/about-github-copilot-for-issues
  issues: true

settings:
  readme:
    includeReadmeContext: true
  chatCompletions:
    includeRepositoryContext: true
  pullRequests:
    automatic:
      summarize: true
      review: true
    suggestionQuality: balanced
  issues:
    automatic:
      suggest: true
      summarize: true

telemetry:
  enabled: false  # Disable telemetry for privacy

security:
  minSecurityLevel: medium
  codeScanning: true
  dependabot: true