version: 1

features:
  chat: true
  cli: true
  workspace: true
  pullRequests: true
  issues: true

settings:
  readme:
    includeReadmeContext: true
  chatCompletions:
    includeRepositoryContext: true
  pullRequests:
    automatic:
      summarize: true
      review: true
    suggestionQuality: balanced
  issues:
    automatic:
      suggest: true
      summarize: true

telemetry:
  enabled: false  # Disable telemetry for privacy

security:
  minSecurityLevel: medium
  codeScanning: true
  dependabot: true