name: GitHub Copilot PR Feedback

on:
  pull_request:
    types: [opened, synchronize]
    
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  copilot-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: GitHub Copilot PR Feedback
        uses: github/copilot-feedback-action@v1
        with:
          version: latest